module:
  name: hello-world
  version: "0.1.0"

services:
  - name: db
    image: postgres:15
    build:
      context: .
      dockerfile: Dockerfile.db
    expose:
      - 5132
    env:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres
    depends_on: []
    volumes:
      - hostPath: ./db/init.sql
        servicePath: /docker-entrypoint-initdb.d/init.sql
      - name: db-data
        servicePath: /var/lib/postgresql/data
    networks:
      - hi-net

  - name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - 8080
    env:
      - key: DB_CONN
        value: postgres://postgres:postgres@hello-world-main-db:5432/postgres?sslmode=disable
    depends_on:
      - db
    networks:
      - hi-net

  - name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    expose:
      - 3000
    publish:
      - 3001
    env:
      - key: BACKEND_URL
        value: http://hello-world-main-backend:8080
    depends_on:
      - backend
    networks:
      - hi-net

volumes:
  - db-data

networks:
  - hi-net